function iaq2elps(ifn,ofn,shffn)
% IAQ2ELPS(ifn,ofn,shffn) loads a .iaq file, applies shift to first two images,
% then interacts with user to define cells. Result is saved as OFN.
% If OFN is empty, it is automatically generated by taking the '.iaq' part of 
% IFN and adding '-imelps.mat'.

if isempty(ofn)
  ofn = [ ifn(1:end-4) '-imelps.mat' ];
end

fprintf(1,'Loading %s...\n',ifn);
x2 = load(ifn,'-mat');
if isempty(shffn)
  shf='';
else
  fprintf(1,'Loading %s...\n',shffn);
  shf = load(shffn);
end

fprintf(1,'Shifting...\n');
x2.optical_data = x2.optical_data(:,:,1:2);
ods = useshift(x2,shf);

if exist(ofn)
  fprintf(1,'Loading %s...\n',ofn);
  elps=load(ofn);
else
  elps.e1=[];
  elps.e2=[];
end

fprintf(1,'Initiating user interaction...\n');
[e1,e2] = twoimelps(ods(:,:,1),ods(:,:,2),ifn,{elps.e1,elps.e2});

if ~isempty(e1) | ~isempty(e2)
  fprintf(1,'Saving %s...\n',ofn);
  save(ofn,'e1','e2');
else
  fprintf(1,'Not saving: no ellipses defined or window closed\n');
end

