function dw_findx_mexall
% DW_FINDX_MEXALL - Compiles all .c files in "findx"

a = which('dw_findx_mexall');
[b,~,~] = splitname(a);
olddir = cd(b);

cc = { ...
  'binsearch_core.c'; ...
  'crossseriesmatch_core.c'; ...
  'findfirst_eq.c'; ...
  'findfirst_ge.c'; ...
  'findfirst_gt.c'; ...
  'findfirst_le.c'; ...
  'findfirst_lt.c'; ...
  'findfirst_ne.c'; ...
  'findlast_eq.c'; ...
  'findlast_ge.c'; ...
  'findlast_gt.c'; ...
  'findlast_le.c'; ...
  'findlast_lt.c'; ...
  'findlast_ne.c'
  };

for c=1:length(cc)
  fprintf(1, 'Compiling %s\n', cc{c});
  mex(cc{c});
end

cd(olddir);
